name: flutter_flavor
description: "We can create different flavors, and thus have different instances of our apps before publishing it on the App Store and Google Play."
version: 3.0.3
homepage: https://github.com/lrferreiro/flutter_flavor

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  xml: ^6.0.1
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
